### ISSUE TITLE
on fedora 28 make dev failed

### ISSUE THREAD

**Issue by yazug** [release-depot/koji_wrapper#17]
* koji_wrapper version: master
* Python version: 2.7.15 and 3.6.5
* Operating System: fedora 28

### Description

I was trying to follow README to get dev environment setup and working, but make dev failed

### What I Did

```
[jschluet@bagend koji_wrapper]$ make dev
pip3 install --user pipenv
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/8d/fe/4faa519acfb984015dde4e2973d89e47baf6a9cd81e9d58e2f2d3c47fb6f/pipenv-2018.5.18-py3-none-any.whl (6.4MB)                                                                           
    100% |████████████████████████████████| 6.4MB 302kB/s
Collecting certifi (from pipenv)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)                                                                      
    100% |████████████████████████████████| 153kB 6.5MB/s
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: virtualenv in /usr/lib/python3.6/site-packages (from pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/lib/python3.6/site-packages (from pipenv)
Installing collected packages: certifi, pipenv
Successfully installed certifi-2018.4.16 pipenv-2018.5.18
pipenv install --dev
make: pipenv: Command not found
make: *** [Makefile:94: dev] Error 127
```

Looks like it installed it into my --user but that is not on my PATH for my shell so it bombed out.

**Comment by jguiditta** [comment]
On my system, I see:
``$ which pipenv
``~/.local/bin/pipenv

and this is indeed on my path.  I don't recall having to set this up myself, but it was some time ago, so I may just be forgetting.  Can you add ~/.local/bin to your path and see if that fixes the issue for you?  If so, we can update the readme to explain that error, which, imo, is a pip error.  It should not have the option to install to a --user location if it is not going to work

**Comment by fuzzball81** [comment]
I know for fish shell I need to explicitly add it to my path, but I expected that. I did not have to do that for bash, this is all on F27.

**Comment by yazug** [comment]
Issue was Pathing, ~/.local/bin was no on the search path so the quickstart/Makefile/tox.ini setup all blew up for me.
