### ISSUE TITLE
RFE: support for KojiTag Object to use koji latest flag when getting list of builds in tag

### ISSUE THREAD

**Issue by yazug** [release-depot/koji_wrapper#26]
This maps to call to koji.listBuilds(tag="", latest=True)

This allows tooling to maybe use KojiTag(tag="", latest=True) vs KojiTag(tag="", [latest=False])

this corresponds to koji list-tagged --latest or koji list-tagged

Use case for this is tag_delta script which allows you to compare versions available between 2 tags and it is useful to configure it for inherit or not depending on the data you want to look at.

**Comment by jguiditta** [comment]
Addressed in PR #36
