### ISSUE TITLE
RFE: support for KojiTag Object to use koji type when listing builds in a given tag

### ISSUE THREAD

**Issue by yazug** [release-depot/koji_wrapper#27]
This maps to call to koji.listBuilds(tag="", type='rpm')

This allows tooling to maybe use
KojiTag(tag="", type='rpm')
KojiTag(tag="", type='image')
KojiTag(tag="", [type='all']) ??

Useful when trying to work with either images or rpms in a given koji tag, or default to everything available.

**Comment by jguiditta** [comment]
Addressed with PR #36
