### ISSUE TITLE
RFE: KojiWrapper/KojiBase update topurl/url from session if present

### ISSUE THREAD

**Issue by yazug** [release-depot/koji_wrapper#28]
In KojiBase it has 3 parameters, url, topurl and session.  The first should be able to be derived from session.  topurl might be able to be derived from url on demand if you talk with the koji session but that is a further optimisation.

**Comment by jguiditta** [comment]
I am not sure how this would work, you cant create a session/KojiClient without know where it and its hub are, which are what url/topurl represent.  They can certainly be omitted if you already have a session object, they are not require params.  Are you trying to get at a case where you need to know their values for an existing KojiClient?  Or something else?

**Comment by jguiditta** [comment]
ok, your example makes perfect sense, this is definitely how you would retrieve the url value - however, I am unclear where this would be needed, or what for?
